### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by GuilhermeKayan** [HelioSilva/Whatsapp-bot-NodeJS#4]
Me tira uma duvida, da para juntar, conectar esse bot com um frontend? no caso um ex, com react, ai pegava o qrcode gerado pelo bot, e jogava no react para a pessoa ler? ai rodava o bot por debaixo dos panos?

**Comment by HelioSilva** [comment]
Olá @GuilhermeKayan , funciona sim, até fiz uma vez uns testes usando socket.io e ficou muito bom. Usando sockets você consegue deixar o seu frontend igual ao Whatsapp web praticamente. Podendo enviar e receber mensagens e tals.
