### ISSUE TITLE
Atualização do bot

### ISSUE THREAD

**Issue by ZaunSupremoXV** [HelioSilva/Whatsapp-bot-NodeJS#5]
Efetuei algumas modificações no código, como faço pra lhe enviar para que possa atualizar aqui no Git?

**Comment by HelioSilva** [comment]
@ZaunSupremoXV , você fez o FORK desse projeto e alterou em cima desse fork? Se sim, basta você subir para o git na sua conta e lá vai aparecer a opção de fazer Pull Request. Basta clicar e solicitar o Pull, mas se não fez pelo fork então me envia o projeto com as alterações como zip(google drive ou outros) que eu faço a alteração. 

Desde já agradeço pela melhoria.

**Comment by HelioSilva** [comment]
Se possível você poderia descrever as modificações que você fez? Porque coloco no changeLOG do projeto.

**Comment by ZaunSupremoXV** [comment]
Atualizei pra versão mais recente do venom-bot; 
Adicionei no stage 0 a opção de identificar se é para dizer "bom dia", "boa tarde" ou "boa noite";
Corrigi um erro que eu tinha na sequencia que era enviadas as mensagens ;
Alterei a maneira de como faz a requisição do arquivo banco.js e stages.js;
Criei duas pastas para deixar mais organizado o local dos arquivos;
Ajustei no package.json o comando `npm start` e o main do projeto.


https://drive.google.com/file/d/1xAly3aWpqYNcP085zuHSqjVn0u1xHIoR/view?usp=sharing

**Comment by HelioSilva** [comment]
@ZaunSupremoXV TOP!!!!!🤝 Vou rodar aqui e atualizar!

**Comment by ZaunSupremoXV** [comment]
Blz, assim que eu fizer novas atualizações lhe notifico novamente.

**Comment by HelioSilva** [comment]
Modificações adicionadas ao projeto!
