### ISSUE TITLE
sendText não funciona sem o onMessage

### ISSUE THREAD

**Issue by ismaelmelkis** [HelioSilva/Whatsapp-bot-NodeJS#6]
Saudações. . .

Meus parabéns pelo conteúdo, está muito bom ...
Estou tentando enviar uma mensagem sem interação com o usuário, apenas o client.sendText (' 5531999999999@c.us ', "Olá Tudo Bem? Que tal um Lanche hoje! Estamos com Promoções Incríveis... Digite Sim caso queira visualizar o cardápio") , mas está aparecendo um erro WAPI não definida ;
Sabe me dizer se isso é uma falha do venom, tentei fazer as atualizações, mas também não funcionou ...

**Comment by HelioSilva** [comment]
Opa, sim esse problema deve está relacionado com o venom, aconcelho atualizar o venom para a útima versão.

**Comment by HelioSilva** [comment]
> Caso esteja com o mesmo problema, pode reabrir a issue.
